controller_list:
  - name: fake_spot_arm_controller
    type: $(arg execution_type)
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
      - arm_joint6
  - name: fake_hand_controller
    type: $(arg execution_type)
    joints:
      - arm_joint6
      - arm_gripper
initial:  # Define initial robot poses.
  - group: spot_arm
    pose: Zero
  - group: hand
    pose: close
