controller_list:
  - name: spot_arm/arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - Rev9
      - Rev8
      - Rev11
      - Rev3
      - Rev10
      - Rev6